---

- hosts: test
  become: true
  
  tasks:
    - name: testtask
      package: name=nano state=present

#- hosts: test
#  become: true
#  tasks:
#    - name: touch_file
#      package: name=nano state=present

